= Biblioteket

== Funktioner och operatorer
=== Next Number

==== Beskrivning
Tar ett heltal som input och ger nästa tal som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | 6

    | 2 | 3

    | -3 | -2

|===

==== Testkörning
[source, ruby, numbered]
----
next_number(5) #=> 6 
next_number(2) #=> 3 
next_number(-3) #=> -2 

----
=== Previous Number

==== Beskrivning
Tar ett heltal som input och ger föregående tal som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | 4

    | 2 | 1

    | -3 | -4

|===

==== Testkörning
[source, ruby, numbered]
----
previous_number(5) #=> 4 
previous_number(2) #=> 1 
previous_number(-3) #=> -4 

----
=== Square

==== Beskrivning
Tar ett heltal som input och ger kvadraten på talet som output. Kvadraten på ett tal innebär talet multiplicerat med sig själv.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | 25

    | 2 | 4

    | -3 | 9

|===

==== Testkörning
[source, ruby, numbered]
----
square(5) #=> 25 
square(2) #=> 4 
square(-3) #=> 9 

----
=== Cube

==== Beskrivning
Tar ett heltal som input och ger kubiken på talet som output. Kubiken på ett tal innebär talet multiplicerat med sig själv tre gånger.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | 125

    | 2 | 8

    | -3 | -27

|===

==== Testkörning
[source, ruby, numbered]
----
cube(5) #=> 125 
cube(2) #=> 8 
cube(-3) #=> -27 

----

== Villkor
=== Is Negative

==== Beskrivning
Tar ett heltal som input och avgör om talet är negativt.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | false

    | 2 | false

    | -3 | true

|===

==== Testkörning
[source, ruby, numbered]
----
is_negative(5) #=> false 
is_negative(2) #=> false 
is_negative(-3) #=> true 

----
=== Is Even

==== Beskrivning
Tar ett heltal som input och avgör om talet är jämnt.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | false

    | 2 | true

    | -10 | true

|===

==== Testkörning
[source, ruby, numbered]
----
is_even(5) #=> false 
is_even(2) #=> true 
is_even(-10) #=> true 

----
=== Is Odd

==== Beskrivning
Tar ett heltal som input och avgör om talet är udda.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | true

    | 2 | false

    | -10 | false

|===

==== Testkörning
[source, ruby, numbered]
----
is_odd(5) #=> true 
is_odd(2) #=> false 
is_odd(-10) #=> false 

----
=== Absolute

==== Beskrivning
Tar ett heltal som input och ger absolutvärdet på talet som output. Absolutvärdet innebär det positiva motsvarigheten av talet.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 5 | 5

    | 100 | 100

    | -200 | 200

    | -10 | 10

|===

==== Testkörning
[source, ruby, numbered]
----
absolute(5) #=> 5 
absolute(100) #=> 100 
absolute(-200) #=> 200 
absolute(-10) #=> 10 

----
=== Between

==== Beskrivning
Tar tre tal som input och avgör om det första ligger mellan den andra och tredje.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | 1| 1| 10 | true

    | 1| 5| 100 | false

    | 0| -1| 1 | true

|===

==== Testkörning
[source, ruby, numbered]
----
between(1, 1, 10) #=> true 
between(1, 5, 100) #=> false 
between(0, -1, 1) #=> true 

----
=== Between Strict

==== Beskrivning
Tar tre tal som input och avgör om det första ligger strikt mellan den andra och tredje.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | 1| 1| 10 | false

    | 1| 5| 100 | false

    | 0| -1| 1 | true

|===

==== Testkörning
[source, ruby, numbered]
----
between_strict(1, 1, 10) #=> false 
between_strict(1, 5, 100) #=> false 
between_strict(0, -1, 1) #=> true 

----
=== Min of Two

==== Beskrivning
Tar två tal som input och ger det minsta av dem som output.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | 100| 20 | 20

    | -2| 10 | -2

    | 0| 1 | 0

|===

==== Testkörning
[source, ruby, numbered]
----
min_of_two(100, 20) #=> 20 
min_of_two(-2, 10) #=> -2 
min_of_two(0, 1) #=> 0 

----
=== Min of Three

==== Beskrivning
Tar tre tal som input och ger det minsta av dem som output

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | 1| 2| 3 | 1

    | 100| 2| 256 | 2

    | 1337| -1337| 0 | -1337

|===

==== Testkörning
[source, ruby, numbered]
----
min_of_three(1, 2, 3) #=> 1 
min_of_three(100, 2, 256) #=> 2 
min_of_three(1337, -1337, 0) #=> -1337 

----
=== Min of Four

==== Beskrivning
Tar fyra som input och ger det minsta av dem som output

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Input 4**| **Output**  

    | 1| 2| 3| 4 | 1

    | 100| 2| 256| 1 | 1

    | 1337| -1337| 0| -1338 | -1338

|===

==== Testkörning
[source, ruby, numbered]
----
min_of_four(1, 2, 3, 4) #=> 1 
min_of_four(100, 2, 256, 1) #=> 1 
min_of_four(1337, -1337, 0, -1338) #=> -1338 

----
=== Max of Two

==== Beskrivning
Tar två tal som input och ger det största av dem som output.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | 100| 20 | 100

    | -2| 10 | 10

    | 0| 1 | 1

|===

==== Testkörning
[source, ruby, numbered]
----
max_of_two(100, 20) #=> 100 
max_of_two(-2, 10) #=> 10 
max_of_two(0, 1) #=> 1 

----
=== Max of Three

==== Beskrivning
Tar tre tal som input och ger det största av dem som output

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | 1| 2| 3 | 3

    | 100| 2| 256 | 256

    | 1337| -1337| 0 | 1337

|===

==== Testkörning
[source, ruby, numbered]
----
max_of_three(1, 2, 3) #=> 3 
max_of_three(100, 2, 256) #=> 256 
max_of_three(1337, -1337, 0) #=> 1337 

----
=== Max of Four

==== Beskrivning
Tar tre fyra som input och ger det största av dem som output

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Input 4**| **Output**  

    | 1| 2| 3| 4 | 4

    | 100| 2| 256| 1 | 256

    | 1337| -1337| 0| -1338 | 1337

|===

==== Testkörning
[source, ruby, numbered]
----
max_of_four(1, 2, 3, 4) #=> 4 
max_of_four(100, 2, 256, 1) #=> 256 
max_of_four(1337, -1337, 0, -1338) #=> 1337 

----

== Loopar
=== Sum To

==== Beskrivning
Tar ett tal som input och ger summan av alla tal från 0 till talet som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 3 | 6

    | 5 | 15

    | 10 | 55

|===

==== Testkörning
[source, ruby, numbered]
----
sum_to(3) #=> 6 
sum_to(5) #=> 15 
sum_to(10) #=> 55 

----
=== Factorial

==== Beskrivning
Tar ett tal som input och ger produkten av alla tal från 1 till talet som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | 3 | 6

    | 5 | 120

    | 10 | 3628800

|===

==== Testkörning
[source, ruby, numbered]
----
factorial(3) #=> 6 
factorial(5) #=> 120 
factorial(10) #=> 3628800 

----
=== Power

==== Beskrivning
Tar två tal som input och ger potensen som output, med första input som bas och andra som exponent.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | 3| 2 | 9

    | 5| 3 | 125

    | 10| 6 | 1000000

|===

==== Testkörning
[source, ruby, numbered]
----
power(3, 2) #=> 9 
power(5, 3) #=> 125 
power(10, 6) #=> 1000000 

----

== Arrayer
=== First Of

==== Beskrivning
Tar en Array som input och ger det första elementet i arrayen som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [1, 2, 3] | 1

    | [1337, 2, -1] | 1337

    | [0, 0, 0] | 0

|===

==== Testkörning
[source, ruby, numbered]
----
first_of([1, 2, 3]) #=> 1 
first_of([1337, 2, -1]) #=> 1337 
first_of([0, 0, 0]) #=> 0 

----
=== Last Of

==== Beskrivning
Tar en Array som input och ger det sista elementet i arrayen som output.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [1, 2, 3] | 3

    | [1337, 2, -1] | -1

    | [0, 0, 0] | 0

|===

==== Testkörning
[source, ruby, numbered]
----
last_of([1, 2, 3]) #=> 3 
last_of([1337, 2, -1]) #=> -1 
last_of([0, 0, 0]) #=> 0 

----
=== Append

==== Beskrivning
Tar en array och ett heltal som input och ger en ny array som output, där hetalet läggs till i slutet på arrayen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [1, 2, 3]| 4 | [1, 2, 3, 4]

|===

==== Testkörning
[source, ruby, numbered]
----
append([1, 2, 3], 4) #=> [1, 2, 3, 4] 

----
=== Concat

==== Beskrivning
Tar två arrayer som input och ger en ny array som output, där båda arrayerna sätts ihop.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [1, 2, 3]| [4, 5, 6] | [1, 2, 3, 4, 5, 6]

    | [10, 10, 10]| [11, 11, 11] | [10, 10, 10, 11, 11, 11]

|===

==== Testkörning
[source, ruby, numbered]
----
concat([1, 2, 3], [4, 5, 6]) #=> [1, 2, 3, 4, 5, 6] 
concat([10, 10, 10], [11, 11, 11]) #=> [10, 10, 10, 11, 11, 11] 

----
=== Prepend

==== Beskrivning
Tar En array och ett heltal som input och ger en ny array som output, där heltalet läggs i början på arrayen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [1, 2, 3]| 4 | [4, 1, 2, 3]

    | [10, 10, 10]| 11 | [11, 10, 10, 10]

|===

==== Testkörning
[source, ruby, numbered]
----
prepend([1, 2, 3], 4) #=> [4, 1, 2, 3] 
prepend([10, 10, 10], 11) #=> [11, 10, 10, 10] 

----
=== Sum

==== Beskrivning
Tar en array av integers som input och ger summan av alla tal som output

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [1, 2, 3, 4, 5] | 15

    | [1337, 1337, 1337] | 4011

|===

==== Testkörning
[source, ruby, numbered]
----
sum([1, 2, 3, 4, 5]) #=> 15 
sum([1337, 1337, 1337]) #=> 4011 

----
=== Average

==== Beskrivning
Tar en array av integers som input och ger medelvärdet av talen som output

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [1, 2, 3, 4, 5] | 3.0

    | [1337, 1337, 1337] | 1337.0

|===

==== Testkörning
[source, ruby, numbered]
----
average([1, 2, 3, 4, 5]) #=> 3.0 
average([1337, 1337, 1337]) #=> 1337.0 

----
=== Is Empty

==== Beskrivning
Tar en sträng som input och avgör om strängen är tom

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | "" | true

    | "hej hopp" | false

|===

==== Testkörning
[source, ruby, numbered]
----
is_empty("") #=> true 
is_empty("hej hopp") #=> false 

----

== Strängar
=== Starts With

==== Beskrivning
Tar en sträng och ett tecken som input och avgör om strängen börjar på det tecknet

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "hej hopp"| "h" | true

    | "Hello World"| "k" | false

    | "!!zomg!!"| "!" | true

|===

==== Testkörning
[source, ruby, numbered]
----
starts_with("hej hopp", "h") #=> true 
starts_with("Hello World", "k") #=> false 
starts_with("!!zomg!!", "!") #=> true 

----
=== Ends With

==== Beskrivning
Tar en sträng och ett tecken som input och avgör om strängen slutar på det tecknet

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "hej hopp"| "p" | true

    | "Hello World"| "W" | false

    | "!!zomg!!"| "!" | true

|===

==== Testkörning
[source, ruby, numbered]
----
ends_with("hej hopp", "p") #=> true 
ends_with("Hello World", "W") #=> false 
ends_with("!!zomg!!", "!") #=> true 

----
=== Chomp

==== Beskrivning
Tar en sträng som input och ger en ny sträng som output, där den eventuellt tagit bort "\n"-tecknet från slutet.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | "hej hopp\n" | "hej hopp"

    | "Hello World!" | "Hello World!"

    | "Foobar\n\n" | "Foobar\n"

|===

==== Testkörning
[source, ruby, numbered]
----
chomp("hej hopp\n") #=> "hej hopp" 
chomp("Hello World!") #=> "Hello World!" 
chomp("Foobar\n\n") #=> "Foobar\n" 

----
=== Contains Char

==== Beskrivning
Tar en sträng och ett tecken som input och avgör om tecknet finns i strängen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "hej hopp"| "h" | true

    | "Hello World"| "%" | false

    | "Hello World"| "H" | true

|===

==== Testkörning
[source, ruby, numbered]
----
contains_char("hej hopp", "h") #=> true 
contains_char("Hello World", "%") #=> false 
contains_char("Hello World", "H") #=> true 

----
=== Index of Char

==== Beskrivning
Tar en sträng och ett tecken som input och ger tecknets position i strängen som output om det finns, annars nil.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "hej hopp"| "h" | 0

    | "Hello World!"| "!" | 11

    | "Hello World"| "!" | nil

|===

==== Testkörning
[source, ruby, numbered]
----
index_of_char("hej hopp", "h") #=> 0 
index_of_char("Hello World!", "!") #=> 11 
index_of_char("Hello World", "!") #=> nil 

----
=== Count

==== Beskrivning
Tar en sträng och ett tecken som input och ger antalet förekomster av tecknet i strängen som output.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "omg omg omg"| "g" | 3

    | "Bananpaj och grillkorv"| "a" | 3

    | ".../o(. .  )"| "." | 5

|===

==== Testkörning
[source, ruby, numbered]
----
count_char("omg omg omg", "g") #=> 3 
count_char("Bananpaj och grillkorv", "a") #=> 3 
count_char(".../o(. .  )", ".") #=> 5 

----
=== Remove

==== Beskrivning
Tar en sträng och ett tecken som input och ger en ny sträng som output, där tecknet är borttaget.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "omg omg omg"| "g" | "om om om"

    | "I am a teapot"| "a" | "I m  tepot"

|===

==== Testkörning
[source, ruby, numbered]
----
remove_char("omg omg omg", "g") #=> "om om om" 
remove_char("I am a teapot", "a") #=> "I m  tepot" 

----
=== Left Strip

==== Beskrivning
Tar en sträng som input och ger en ny sträng som output, där all whitespace på vänster sida är borttaget. (whitespace inkluderar mellanslag" ", tabbar \t och radbrytningar \n)

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | "   Hello World!  " | "Hello World!  "

    | "\tFoobar" | "Foobar"

    | "\nTesttest\n" | "Testtest\n"

|===

==== Testkörning
[source, ruby, numbered]
----
left_strip("   Hello World!  ") #=> "Hello World!  " 
left_strip("\tFoobar") #=> "Foobar" 
left_strip("\nTesttest\n") #=> "Testtest\n" 

----
=== Right Strip

==== Beskrivning
Tar en sträng som input och ger en ny sträng som output, där all whitespace på höger sida är borttaget. (whitespace inkluderar mellanslag" ", tabbar \t och radbrytningar \n)

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | "   Hello World!  " | "   Hello World!"

    | "\tFoobar" | "\tFoobar"

    | "\nTesttest\n" | "\nTesttest"

|===

==== Testkörning
[source, ruby, numbered]
----
right_strip("   Hello World!  ") #=> "   Hello World!" 
right_strip("\tFoobar") #=> "\tFoobar" 
right_strip("\nTesttest\n") #=> "\nTesttest" 

----
=== Strip

==== Beskrivning
Tar en sträng som input och ger en ny sträng som output, där all whitespace på båda sidor är borttaget. (whitespace inkluderar mellanslag" ", tabbar \t och radbrytningar \n)

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | "   Hello World!  " | "Hello World!"

    | "\tFoobar" | "Foobar"

    | "\nTesttest\n" | "Testtest"

|===

==== Testkörning
[source, ruby, numbered]
----
strip("   Hello World!  ") #=> "Hello World!" 
strip("\tFoobar") #=> "Foobar" 
strip("\nTesttest\n") #=> "Testtest" 

----
=== Replace Char

==== Beskrivning
Tar tre strängar som input och en ny sträng som output där alla förekomster av sträng2 i sträng1 är ersatt med sträng3

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | "Hello World!"| "H"| "F" | "Fello World!"

    | "Foobar"| "F"| "B" | "Boobar"

|===

==== Testkörning
[source, ruby, numbered]
----
replace_char("Hello World!", "H", "F") #=> "Fello World!" 
replace_char("Foobar", "F", "B") #=> "Boobar" 

----
=== Slice

==== Beskrivning
Tar en sträng och två integers som input och ger en ny sträng som output, där alla tecken i strängen mellan talen är urklippta.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | "Hello World"| 2| 8 | "llo Wo"

    | "Foobar"| 0| 1 | "F"

|===

==== Testkörning
[source, ruby, numbered]
----
slice("Hello World", 2, 8) #=> "llo Wo" 
slice("Foobar", 0, 1) #=> "F" 

----
=== Split Char

==== Beskrivning
Tar en sträng och ett tecken som input och ger en array som output, där elementen i arrayen är alla delar av strängen som är avskiljda med tecknet

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "1;2;3;4;5"| ";" | ["1", "2", "3", "4", "5"]

    | "Hello World"| " " | ["Hello", "World"]

    | "This is a line\nthis is another line\nthis is a line too"| "\n" | ["This is a line", "this is another line", "this is a line too"]

|===

==== Testkörning
[source, ruby, numbered]
----
split_char("1;2;3;4;5", ";") #=> ["1", "2", "3", "4", "5"] 
split_char("Hello World", " ") #=> ["Hello", "World"] 
split_char("This is a line\nthis is another line\nthis is a line too", "\n") #=> ["This is a line", "this is another line", "this is a line too"] 

----

== Mer Arrayer
=== Filter

==== Beskrivning
Tar en array och ett värde som input och ger en ny array som output, där den nya arrayen endast innehåller värdet.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [8, 2, 0, 2, 5]| "2" | []

    | ["bosse", "olof", "kalle", "olof"]| "olof" | ["olof", "olof"]

|===

==== Testkörning
[source, ruby, numbered]
----
filter([8, 2, 0, 2, 5], "2") #=> [] 
filter(["bosse", "olof", "kalle", "olof"], "olof") #=> ["olof", "olof"] 

----
=== Exclude

==== Beskrivning
Tar en array och ett värde som input och ger en ny array som output, där den nya arrayen **inte** innehåller värdet.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [8, 2, 0, 2, 5]| "2" | [8, 2, 0, 2, 5]

    | ["bosse", "olof", "kalle", "olof"]| "olof" | ["bosse", "kalle"]

|===

==== Testkörning
[source, ruby, numbered]
----
exclude([8, 2, 0, 2, 5], "2") #=> [8, 2, 0, 2, 5] 
exclude(["bosse", "olof", "kalle", "olof"], "olof") #=> ["bosse", "kalle"] 

----
=== Unique

==== Beskrivning
Tar en array som input och en ny array som output, där den nya arrayen inte innehåller några dubletter.

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [8, 2, 0, 2, 5] | [8, 2, 0, 5]

    | ["bosse", "olof", "kalle", "olof"] | ["bosse", "olof", "kalle"]

|===

==== Testkörning
[source, ruby, numbered]
----
unique([8, 2, 0, 2, 5]) #=> [8, 2, 0, 5] 
unique(["bosse", "olof", "kalle", "olof"]) #=> ["bosse", "olof", "kalle"] 

----
=== Count

==== Beskrivning
Tar en array och ett värde som input och ger antalet förekomster av värdet i arrayen som output

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [8, 2, 0, 2, 5, 0, 0, 0]| 0 | 4

    | ["bosse", "olof", "kalle", "olof"]| "olof" | 2

|===

==== Testkörning
[source, ruby, numbered]
----
count([8, 2, 0, 2, 5, 0, 0, 0], 0) #=> 4 
count(["bosse", "olof", "kalle", "olof"], "olof") #=> 2 

----
=== Contains

==== Beskrivning
Tar en array och ett värde som input och av gör om arrayen innehåller värdet

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | [8, 2, 0, 2, 5, 0, 0, 0]| 0 | true

    | ["bosse", "olof", "kalle", "olof"]| "gunilla" | false

|===

==== Testkörning
[source, ruby, numbered]
----
contains([8, 2, 0, 2, 5, 0, 0, 0], 0) #=> true 
contains(["bosse", "olof", "kalle", "olof"], "gunilla") #=> false 

----

== Mer Strängar
=== Contains String

==== Beskrivning
Tar två strängar som input och avgör om den första strängen innehåller den andra strängen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "foobar"| "bar" | true

    | "foobar"| "baz" | false

|===

==== Testkörning
[source, ruby, numbered]
----
contains_string("foobar", "bar") #=> true 
contains_string("foobar", "baz") #=> false 

----
=== Index String

==== Beskrivning
Tar två strängar som input och ger positionen av den andra strängen i den första strängen som output.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "foobar"| "bar" | 3

    | "foobar"| "baz" | nil

|===

==== Testkörning
[source, ruby, numbered]
----
index_string("foobar", "bar") #=> 3 
index_string("foobar", "baz") #=> nil 

----
=== Count String

==== Beskrivning
Tar två strängar som input och ger antalet förekomster av den andra strängen i den första strängen som output.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "omg omg omg"| "omg" | 3

    | "examples are hard\nexamples are hard\nexamples are hard"| "examples" | 3

|===

==== Testkörning
[source, ruby, numbered]
----
count_string("omg omg omg", "omg") #=> 3 
count_string("examples are hard\nexamples are hard\nexamples are hard", "examples") #=> 3 

----
=== Remove String

==== Beskrivning
Tar två strängar som input och ger en sträng som output, där den nya strängen inte innehåller den andra strängen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "omg omg omg"| " " | "omgomgomg"

    | "this is a test"| " test" | "this is a"

|===

==== Testkörning
[source, ruby, numbered]
----
remove_string("omg omg omg", " ") #=> "omgomgomg" 
remove_string("this is a test", " test") #=> "this is a" 

----
=== Replace String

==== Beskrivning
Tar tre strängar som input och ger en sträng som output, där den nya strängen har varje förekomst av sträng2 ersatt av sträng3.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Input 3**| **Output**  

    | "omg omg omg"| "omg"| "foo" | "foo foo foo"

    | "examples are hard"| "hard"| "tough" | "examples are tough"

|===

==== Testkörning
[source, ruby, numbered]
----
replace_string("omg omg omg", "omg", "foo") #=> "foo foo foo" 
replace_string("examples are hard", "hard", "tough") #=> "examples are tough" 

----
=== Split String

==== Beskrivning
Tar två strängar som input och en array som output där arrayen innehåller delarna av strängen avgränsat med den andra strängen.

==== Testdata
[width=75%]
|===
 | **Input 1**| **Input 2**| **Output**  

    | "a bunch of text"| " " | ["a", "bunch", "of", "text"]

    | "This is a line\nthis is another line\nthis is also a line"| "\n" | ["This is a line", "this is another line", "this is also a line"]

|===

==== Testkörning
[source, ruby, numbered]
----
split_string("a bunch of text", " ") #=> ["a", "bunch", "of", "text"] 
split_string("This is a line\nthis is another line\nthis is also a line", "\n") #=> ["This is a line", "this is another line", "this is also a line"] 

----

== Sorteringsalgoritmer
=== Selection Sort

==== Beskrivning
Tar en array som input och ger en ny array som output, där arrayen är sorterad i storleksordning. Funktionen följer algoritmen för https://en.wikipedia.org/wiki/Selection_sort[Selection Sort].

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [7, 3, 1, 3] | [1, 3, 3, 7]

    | [0, -1, 2, -1, 9, -1] | [-1, -1, -1, 0, 2, 9]

|===

==== Testkörning
[source, ruby, numbered]
----
selection_sort([7, 3, 1, 3]) #=> [1, 3, 3, 7] 
selection_sort([0, -1, 2, -1, 9, -1]) #=> [-1, -1, -1, 0, 2, 9] 

----
=== Insertion Sort

==== Beskrivning
Tar en array som input och ger en ny array som output, där arrayen är sorterad i storleksordning. Funktionen följer algoritmen för https://en.wikipedia.org/wiki/Insertion_sort[Insertion Sort].

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [7, 3, 1, 3] | [1, 3, 3, 7]

    | [0, -1, 2, -1, 9, -1] | [-1, -1, -1, 0, 2, 9]

|===

==== Testkörning
[source, ruby, numbered]
----
insertion_sort([7, 3, 1, 3]) #=> [1, 3, 3, 7] 
insertion_sort([0, -1, 2, -1, 9, -1]) #=> [-1, -1, -1, 0, 2, 9] 

----
=== Bubble Sort

==== Beskrivning
Tar en array som input och ger en ny array som output, där arrayen är sorterad i storleksordning. Funktionen följer algoritmen för https://en.wikipedia.org/wiki/Bubble_sort[Bubble Sort].

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [7, 3, 1, 3] | [1, 3, 3, 7]

    | [0, -1, 2, -1, 9, -1] | [-1, -1, -1, 0, 2, 9]

|===

==== Testkörning
[source, ruby, numbered]
----
bubble_sort([7, 3, 1, 3]) #=> [1, 3, 3, 7] 
bubble_sort([0, -1, 2, -1, 9, -1]) #=> [-1, -1, -1, 0, 2, 9] 

----
=== Quick Sort

==== Beskrivning
Tar en array som input och ger en ny array som output, där arrayen är sorterad i storleksordning. Funktionen följer algoritmen för https://en.wikipedia.org/wiki/Quicksort[Quick Sort].

==== Testdata
[width=75%]
|===

| **Input** | **Output** 


    | [7, 3, 1, 3] | [1, 3, 3, 7]

    | [0, -1, 2, -1, 9, -1] | [-1, -1, -1, 0, 2, 9]

|===

==== Testkörning
[source, ruby, numbered]
----
quick_sort([7, 3, 1, 3]) #=> [1, 3, 3, 7] 
quick_sort([0, -1, 2, -1, 9, -1]) #=> [-1, -1, -1, 0, 2, 9] 

----
